/**
 * playbook-cycle.ts — the nightly research cycle (LOCAL cron, deterministic).
 *
 * Runs ON this box (needs local parquet + the dashboard JSON the sweeps write).
 * It does NOT re-run backtests; it ATTRIBUTES the per-day P&L the sweeps already
 * produced to regimes, applies a strict chronological train/test split per
 * regime, and rebuilds the playbook matrix. Strategy data is generated by
 * interactive sessions (sweeps → spread-daily*.json); this cron maintains the
 * regime-validated playbook on top of it.
 *
 * PER-TRADE NORMALIZATION (critical): the daily file only carries per-DATE P&L,
 * but variants fire wildly different trade counts per day (a 0DTE iron condor
 * fires ~55×/day; an SMC sweep ~1×/day). Ranking per-day would structurally
 * favor high-frequency structures. So we divide each variant's regime P&L by its
 * estimated trade count: tradesPerDay = n_total / activeDaysTotal (n from the
 * sweep-sweep row; activeDaysTotal = nonzero days in its daily series), then
 * est_trades = traded_days × tradesPerDay. Expectancy is reported PER TRADE.
 *
 * Per symbol (SPX, NDX):
 *   1. Load regimes-{sym}.json (date → primary regime, chronological).
 *   2. Load spread-daily{suffix}.json + spread-sweep{suffix}.json (for n).
 *   3. For each regime: dates in order, chronological 70/30 split. For every
 *      variant compute train/test PER-TRADE expectancy. CONFIRMED iff
 *      train_pt>0 AND test_pt>0 AND est_test_trades>=MIN_TEST_TRADES.
 *   4. Rebuild matrix[sym][regime] (ranked by test per-trade), recompute
 *      uncovered, append a theory_log entry.
 *
 * Realistic fills are whatever the feeding sweeps used (SPX iron ≈ 0.10/leg is
 * acceptable for liquid SPXW; NDX wants 0.65 — that's a sweep-side concern, not
 * this cycle's). WR is recorded as a day-win-rate for context only; it is NOT a
 * pass criterion (negative-skew rule).
 */
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '../../..');
const PB_DIR = path.join(ROOT, 'scripts/autoresearch/playbook');
const OUT_DIR = path.join(ROOT, 'scripts/autoresearch/output');

const MIN_TEST_TRADES = 10;  // min ESTIMATED trades in the test split to confirm
const TOP_PER_REGIME = 3;
const REGIMES = ['gap_go', 'gap_fade', 'gap_chop', 'trend', 'trend_vol', 'chop', 'quiet_range', 'mixed'];

interface DailyFile { dates: string[]; series: Record<string, number[]>; }

function suffix(sym: string): string { return sym === 'SPX' ? '' : `-${sym.toLowerCase()}`; }
function dailyFileFor(sym: string): string { return path.join(OUT_DIR, `spread-daily${suffix(sym)}.json`); }
function sweepFileFor(sym: string): string { return path.join(OUT_DIR, `spread-sweep${suffix(sym)}.json`); }

interface Cell {
  variant: string;
  train_per_trade: number; test_per_trade: number;
  est_test_trades: number; trades_per_day: number;
  dollar_per_day_test: number; day_win_rate: number;
  status: string;
}

// variant key → total trade count `n` from the sweep-sweep rows.
function loadTradeCounts(sym: string): Map<string, number> {
  const m = new Map<string, number>();
  try {
    const rows = JSON.parse(fs.readFileSync(sweepFileFor(sym), 'utf8'));
    for (const r of rows) {
      const key = `${r.signal}|${r.spread}|${r.exit}`;
      if (typeof r.n === 'number') m.set(key, r.n);
    }
  } catch { /* no sweep file → per-trade falls back to per-day (tradesPerDay=1) */ }
  return m;
}

function buildSymbol(sym: string): { matrix: Record<string, Cell[]>; uncovered: string[] } | null {
  let regimes: any[]; let daily: DailyFile;
  try { regimes = JSON.parse(fs.readFileSync(path.join(PB_DIR, `regimes-${sym.toLowerCase()}.json`), 'utf8')); }
  catch { console.error(`[${sym}] no regimes file — skip`); return null; }
  try { daily = JSON.parse(fs.readFileSync(dailyFileFor(sym), 'utf8')); }
  catch { console.error(`[${sym}] no daily file — skip`); return null; }

  const tradeCounts = loadTradeCounts(sym);
  const dateIdx = new Map<string, number>(); daily.dates.forEach((d, i) => dateIdx.set(d, i));

  // Per-variant trades/day = n_total / (nonzero days across full series). Falls
  // back to 1 (per-trade == per-day) when n is unavailable.
  const tradesPerDay = new Map<string, number>();
  for (const [key, arr] of Object.entries(daily.series)) {
    const activeDays = arr.reduce((s, p) => s + (p !== 0 ? 1 : 0), 0);
    const n = tradeCounts.get(key);
    tradesPerDay.set(key, n && activeDays > 0 ? n / activeDays : 1);
  }

  const matrix: Record<string, Cell[]> = {};
  const uncovered: string[] = [];

  for (const regime of REGIMES) {
    const regDates = regimes.filter(r => r.primary === regime).map(r => r.date)
      .filter(d => dateIdx.has(d)).sort();
    if (regDates.length < 4) { uncovered.push(regime); matrix[regime] = []; continue; }
    const cut = Math.floor(regDates.length * 0.7);
    const trainIdx = regDates.slice(0, cut).map(d => dateIdx.get(d)!);
    const testIdx = regDates.slice(cut).map(d => dateIdx.get(d)!);

    const cells: Cell[] = [];
    for (const [variant, arr] of Object.entries(daily.series)) {
      const tpd = tradesPerDay.get(variant)!;
      let trS = 0, trD = 0, teS = 0, teD = 0, teW = 0;
      for (const i of trainIdx) { const p = arr[i] || 0; if (p !== 0) { trS += p; trD++; } }
      for (const i of testIdx)  { const p = arr[i] || 0; if (p !== 0) { teS += p; teD++; if (p > 0) teW++; } }
      if (trD === 0 || teD === 0) continue;
      const estTrTrades = trD * tpd, estTeTrades = teD * tpd;
      if (estTeTrades < MIN_TEST_TRADES) continue;
      const trainPT = trS / estTrTrades, testPT = teS / estTeTrades;
      if (trainPT > 0 && testPT > 0) {
        cells.push({
          variant,
          train_per_trade: +trainPT.toFixed(1),
          test_per_trade: +testPT.toFixed(1),
          est_test_trades: Math.round(estTeTrades),
          trades_per_day: +tpd.toFixed(1),
          dollar_per_day_test: +(teS / teD).toFixed(0),
          day_win_rate: +(100 * teW / teD).toFixed(0),
          status: 'confirmed',
        });
      }
    }
    cells.sort((a, b) => b.test_per_trade - a.test_per_trade);
    matrix[regime] = cells.slice(0, TOP_PER_REGIME);
    if (matrix[regime].length === 0) uncovered.push(regime);
  }
  return { matrix, uncovered };
}

function main() {
  const pbPath = path.join(PB_DIR, 'playbook.json');
  const pb = JSON.parse(fs.readFileSync(pbPath, 'utf8'));
  const today = process.env.PLAYBOOK_DATE || new Date().toISOString().slice(0, 10);

  const summary: string[] = [];
  for (const sym of ['SPX', 'NDX']) {
    const built = buildSymbol(sym);
    if (!built) continue;
    pb.matrix[sym] = built.matrix;
    pb.uncovered[sym] = built.uncovered;
    const covered = Object.values(built.matrix).filter((c: any) => c.length > 0).length;
    summary.push(`${sym}: ${covered}/${REGIMES.length} regimes covered; uncovered=[${built.uncovered.join(',')}]`);
    console.log(`\n[${sym}] regime coverage — PER-TRADE expectancy (OOS, est_test_trades>=${MIN_TEST_TRADES}):`);
    for (const regime of REGIMES) {
      const t = built.matrix[regime]?.[0];
      console.log(`  ${regime.padEnd(13)} ${t
        ? `${t.variant}  train $${t.train_per_trade}/t  test $${t.test_per_trade}/t  (${t.est_test_trades} tr, ${t.trades_per_day}/day, day-wr ${t.day_win_rate})`
        : '— STAND ASIDE (no OOS-positive strategy)'}`);
    }
  }

  pb.version = (pb.version || 1) + 1;
  pb.updated = today;
  pb.theory_log = pb.theory_log || [];
  pb.theory_log.push({ date: today, theory: 'nightly regime-attribution + per-trade OOS rebuild', result: summary.join(' | '), action: 'matrix rebuilt; expectancy normalized per-trade (n/activeDays)' });
  fs.writeFileSync(pbPath, JSON.stringify(pb, null, 2));
  console.log(`\nplaybook.json updated (v${pb.version}). ${summary.join(' | ')}`);
}

main();
